[tools]
"aqua:editorconfig-checker/editorconfig-checker" = "3.8.0"
"aqua:securego/gosec" = "2.27.1"
go = "1.26"
"go:github.com/golangci/golines" = "0.15.0"
"go:golang.org/x/vuln/cmd/govulncheck" = "1.6.0"
gofumpt = "0.10.0"
hk = "1.50.0"
just = "1.56.0"
pkl = "0.32.0"
prettier = "3.9.5"
staticcheck = "2026.1"
