[tools]
"aqua:editorconfig-checker/editorconfig-checker" = "3.8.0"
"aqua:securego/gosec" = "2.28.0"
go = "1.26"
"go:github.com/golangci/golines" = "0.15.0"
"go:golang.org/x/vuln/cmd/govulncheck" = "1.6.0"
gofumpt = "0.10.0"
hk = "1.53.0"
just = "1.57.0"
pkl = "0.32.1"
prettier = "3.9.6"
staticcheck = "2026.1"
