[tools]
"aqua:editorconfig-checker/editorconfig-checker" = "3.6.1"
"aqua:securego/gosec" = "2.25.0"
go = "1.26"
"go:github.com/golangci/golines" = "0.15.0"
"go:golang.org/x/vuln/cmd/govulncheck" = "1.1.4"
gofumpt = "0.9.2"
hk = "1.39.0"
just = "1.48.1"
pkl = "0.31.1"
prettier = "3.8.1"
staticcheck = "2026.1"
